---
es_version: "7.8.0"
#es_use_snapshot_release: false
oss_version: false
default_file: "/etc/sysconfig/elasticsearch"
es_home: "/usr/share/elasticsearch"
use_system_d: true
m_lock_enabled: false
sysd_config_file: "/etc/systemd/system/elasticsearch.service.d/override.conf"
es_package_name: "elasticsearch"
es_version_lock: false
es_start_service: true
es_java_install: "{{ false if (es_version is version('7.0.0', '>=')) else true }}"
update_java: false
es_restart_on_change: true
es_plugins_reinstall: false
es_templates: false
es_user: elasticsearch
es_user_id: 1234
es_group: elasticsearch
es_group_id: 1234
es_config: {}
es_config_default: "elasticsearch.j2"
es_config_log4j2: ""
es_config_jvm: "jvm.options.j2"
#Need to provide default directories
es_conf_dir: "/etc/elasticsearch"
es_pid_dir: "/var/run/elasticsearch"
es_data_dirs:
  - "/opt/elasticsearch"
es_log_dir: "/var/log/elasticsearch"
es_action_auto_create_index: true
es_max_open_files: 65536
es_max_map_count: 262144
es_allow_downgrades: false
es_xpack_trial: false
#These are used for internal operations performed by ansible.
#They do not affect the current configuration
es_api_scheme: "http"
es_api_host: "localhost"
es_api_port: 9200
es_api_uri: "{{ es_api_scheme }}://{{ es_api_host }}:{{ es_api_port }}"
es_security_api: "{{ '_security' if es_version is version('7.0.0', '>=') else '_xpack/security' }}"
es_license_api: "{{ '_license' if es_version is version('7.0.0', '>=') else '_xpack/license' }}"
es_api_sleep: 15

# JVM custom parameters
es_java_home: ''
es_jvm_custom_parameters: ''
es_heap_dump_path: "/var/lib/elasticsearch"


# SSL/TLS parameters
#es_enable_auto_ssl_configuration: true
#es_enable_http_ssl: true
#es_enable_transport_ssl: false
#es_ssl_certificate_ca:
es_ssl_keystore: ""
es_ssl_keystore_password: ""
es_ssl_truststore: ""
es_ssl_truststore_password: ""
es_ssl_key: ""
es_ssl_key_password: ""
es_ssl_certificate: ""
es_ssl_certificate_authority: ""
es_ssl_certificate_path: "{{ es_conf_dir }}/certs"
es_ssl_verification_mode: "certificate"
es_validate_certs: "yes"
es_delete_unmanaged_file: true
es_delete_unmanaged_native: true

## User Config
es_api_basic_auth_user: "<user>"
es_api_basic_auth_password: "<password>"

## certs
es_transport_key: "common.key"
es_transport_cert: "common.crt"
es_transport_ca: "ca.crt"
