- hosts: appservers
  become: yes
  tasks:
    - name: install apache
      yum:
        name: "{{ pkg_name }}"
        state: latest
    - name: Start and enable httpd
      service:
        name: "{{service_name }}"
        state: started
        enabled: yes
    - name: Create index.html
      file:
        path: "{{ index_file_path }}"
        state: touch
    - name: Add a line to index.html
      lineinfile:
        path: "{{ index_file_path }}"
        line: "Hello World"

