---
es_custom_package_url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.8.0-x86_64.rpm"
es_data_dirs: "/opt/elasticsearch/data"
es_log_dir: "/opt/elasticsearch/logs"
es_config:
  node.name: "{{ ansible_fqdn }}"
  cluster.name: "efk"
  cluster.initial_master_nodes: ["<initial master nodes>"]
  discovery.seed_hosts: ["<seed hosts>"]
  http.port: 9200
  transport.port: 9300
  node.data: "{{ data }}"
  node.master: "{{ master }}"
  bootstrap.memory_lock: false
  network.host: "0.0.0.0"
es_enable_http_ssl: true
es_ssl_key: "cert.key"
es_ssl_certificate: "cert.crt"
es_ssl_certificate_ca: "root-ca.crt."
es_heap_size: 2G
es_api_port: 9200
